<?php
session_start();
require_once('../../vendor/autoload.php');
require_once('../../helpers/auth.php');
require_once('../../config/config.php');

$path = '../../public/img/letter_head.png';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);

use Dompdf\Dompdf;

$dompdf = new Dompdf();

$html =
    '
        <!DOCTYPE html>
            <html>
                <head>
                    <meta name="" content="XYZ,0,0,1" />
                    <style type="text/css">
                        table {
                            font-size: 12px;
                            padding: 4px;
                        }

                        th {
                            text-align: left;
                            padding: 4pt;
                        }

                        td {
                            padding: 5pt;
                        }

                        #b_border {
                            border-bottom: dashed thin;
                        }

                        legend {
                            color: #0b77b7;
                            font-size: 1.2em;
                        }

                        #error_msg {
                            text-align: left;
                            font-size: 11px;
                            color: red;
                        }

                        .header {
                            margin-bottom: 20px;
                            width: 100%;
                            text-align: left;
                            position: absolute;
                            top: 0px;
                        }

                        .footer {
                            width: 100%;
                            text-align: center;
                            position: fixed;
                            bottom: 5px;
                        }

                        #no_border_table {
                            border: none;
                        }

                        #bold_row {
                            font-weight: bold;
                        }

                        #amount {
                            text-align: right;
                            font-weight: bold;
                        }

                        .pagenum:before {
                            content: counter(page);
                        }

                        /* Thick red border */
                        hr.red {
                            border: 1px solid red;
                        }
                        .list_header{
                            font-family: "Times New Roman", Times, serif;
                        }
                    </style>
                </head>

                <body style="margin:1px;">
                    <div class="footer">
                        <hr>
                        <i> This document has been generated by ' . $_SESSION['user_name'] . '  On ' . date('d M Y g:ia') . '</i>
                    </div> 
                    <div class="list_header" align="center">
                        <h3>
                            <hr style="width:100%" , color=black><br>
                            List of all Loan products <br>
                        </h3>                        
                    </div>
                    <table border="1" cellspacing="0" width="100%" style="font-size:9pt">
                        <thead>
                            <tr>
                                <th style="width:10%">S/N</th>
                                <th style="width:100%">Loan name</th>
                                <th style="width:50%">Loan interest (%)</th>
                                <th style="width:50%">Loan duration (Months)</th>
                                <th style="width:80%">Maximum limit</th>
                                <th style="width:60%">Loan guarantors</th>
                                <th style="width:100%">Loan description</th>
                            </tr>
                        </thead>
                        <tbody>
                            ';
                                $pdf_sql = mysqli_query(
                                    $mysqli,
                                    "SELECT p.* FROM products p"
                                );
                                if (mysqli_num_rows($pdf_sql) > 0) {
                                    $count = 1;
                                    while ($row = mysqli_fetch_array($pdf_sql)) {
                                        $html .= '<tr>';
                                        // Output each column value in a table cell
                                        $html .= '<td>' . $count . '</td>';
                                        $html .= '<td>' . $row['loan_name'] . '</td>';
                                        $html .= '<td>' . $row['loan_interest'] . '</td>';
                                        $html .= '<td>' . $row['loan_duration'] . '</td>';
                                        $html .= '<td>Ksh' . number_format($row['maximum_limit'], 2) . '</td>';
                                        $html .= '<td>' . $row['loan_guarantors'] . '</td>';
                                        $html .= '<td>' . $row['loan_description'] . '</td>';
                                        $html .= '</tr>';
                                        $count++;
                                    }
                                } else {
                                    // No records found
                                    $html .= '<tr><td colspan="9">No records found</td></tr>';
                                }
                                
                                $html .= '
                        </tbody>
                    </table>
                </body>
            </html>
    ';
$dompdf = new Dompdf();
$dompdf->load_html($html);
$dompdf->set_paper('A4', 'landscape');
$dompdf->set_option('isHtml5ParserEnabled', true);
$dompdf->render();
$dompdf->stream('List of all loan products ' . date('d M Y, g:ia'), array("Attachment" => 1));
$options = $dompdf->getOptions();
$options->setDefaultFont('');
$dompdf->setOptions($options);
?>